#包名/三方插件的库名
name: wechatdemo

#三方插件的描述
description: A new Flutter application.

#版本号+内部版本号
version: 1.0.0+1

#版本控制
environment:
  #dart版本
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"
  #flutter版本
#  flutter: "1.22.0"

#依赖库
dependencies:
  #sdk
  flutter:
    sdk: flutter
  #icon库
  cupertino_icons: ^0.1.2
  #网络库
  http: 0.13.4
  #网络库
  dio: ^4.0.6

#运行时依赖库
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #使用Material Icons字体
  uses-material-design: true

  #资源路径
  assets:
    - images/